services:
  typesense-dashboard:
    container_name: typesense-dashboard
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
